name = "hlawka-schatten"
version = "0.1.0"
keywords = ["math"]
defaultTargets = [
  "HlawkaSchatten", "ExistenceChallenge", "ExistenceSolution",
  "ConstructionDiagonalChallenge", "ConstructionDiagonalSolution"
]

[leanOptions]
weak.linter.mathlibStandardSet = true
autoImplicit = false
relaxedAutoImplicit = false
linter.unusedVariables = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0"

[[lean_lib]]
name = "HlawkaSchatten"

[[lean_lib]]
name = "ExistenceChallenge"

[[lean_lib]]
name = "ExistenceSolution"

[[lean_lib]]
name = "ConstructionDiagonalChallenge"

[[lean_lib]]
name = "ConstructionDiagonalSolution"
